### ISSUE TITLE
snf-ganeti-eventd doesn't automatically ensure it's running on the latest master node

### ISSUE THREAD

**Issue by rowanthorpe** [grnet/synnefo#267]
Redacted email thread explaining the issue:

> > [me] wrote:
> > While working on a wrapper tool for automating rolling reboots
> > ..[snip]..
> > after a master-failover, snf-ganeti-eventd needs to be manually stopped on the old
> > master and started on the new master. This is not such an issue when manually
> > wrangling a cluster, but becomes a show-stopper when automating the process
> > ..[snip]..
> > synnefo is not being an entirely "transparent" layer on Ganeti.
> 
> [Synnefo dev] wrote:
> you are right, currently you have to manually start the snf-ganeti-eventd daemon in
> the new Ganeti master. As you mention, because master-failover is not done
> automatically, this is not a big issue.
> 
> The problem is that master-failover does not run as a Ganeti job and Ganeti does
> not provide a hook to run in this case.
> ..[snip]..
> 
> Can you create an issue to track the progress of this feature ?
> 
> Also, I should mention that snf-ganeti-eventd can run in more than one
> master-candidate nodes, which however results in more messages to the
> RabbitMQ broker.

**Comment by skalkoto** [comment]
fixed
