### ISSUE TITLE
Double tag </body> on home page of pithos ( html markup )

### ISSUE THREAD

**Issue by odesk2dot2by** [grnet/synnefo#378]
Double tag </body> on home page of pithos ( html markup )
Look on screenshot

![selection_001](https://cloud.githubusercontent.com/assets/7859007/17073036/d84a364e-5075-11e6-8562-91ac6f610f10.png)

**Comment by philipgian** [comment]
Thanks for reporting this. It is fixed in https://github.com/grnet/snf-ui-app/commit/bb5d04365d978c52adcec4a6eb683761178e3ca3.
